slam_toolbox:
  ros__parameters:
    # Режим: mapping или localization
    mode: mapping

    # Топики
    topic_name: /scan
    # odom_topic: /odom

    # TF
    base_frame: base_link
    odom_frame: odom
    map_frame: map

    # Настройки LiDAR
    max_laser_range: 7.0
    laser_min_range: 0.2
    laser_min_angle: -0.785398163
    laser_max_angle: 0.785398163
    laser_beams: 360

    # Параметры алгоритма
    transform_publish_period: 0.1  # 50 Hz
    map_update_interval: 0.5        # обновление карты каждые 2 сек
    resolution: 0.05                # разрешение карты в метрах (5 см)

    # # Параметры odometry
    # use_scan_matching: true
    # use_scan_barycenter: true
    # use_odom: true

    # Параметры фильтрации
    minimum_travel_distance: 0.01
    minimum_travel_heading: 0.01

    # Визуализация
    publish_occupancy_map: true
    publish_debug: false

    # Подавление шума
    do_loop_closing: true
    loop_closure_min_response: 0.8
    loop_closure_rejection_threshold: 2.0

    # Точность скан-матчинга
    scan_downsample_factor: 1        # 1 = без даунсэмплинга
    laser_likelihood_max_dist: 2.0   # макс. расстояние для соответствия

    # Размер карты (если робот в маленькой комнате)
    # max_laser_range: 10.0